### ISSUE TITLE
Null pointer exception on server close (Sponge)

### ISSUE THREAD

**Issue by JamieS1211** [KaiKikuchi/SynX#3]
When closing the server the disable method causes a null pointer exception. The output is below.

`[03:04:12] [Server thread/ERROR] [Sponge]: Could not pass GameStoppingEvent$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@7d0c7df8
java.lang.NullPointerException
        at net.kaikk.mc.synx.sponge.SynXSponge.disable(SynXSponge.java:69) ~[SynXSponge.class:?]
        at net.kaikk.mc.synx.sponge.SynXSponge.onServerStop(SynXSponge.java:48) ~[SynXSponge.class:?]
        at org.spongepowered.common.event.listener.GameStoppingEventListener_SynXSponge_onServerStop1.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.8.9-1890-4.2.0-BETA-1538]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:206) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1538]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:247) [SpongeModEventManager.class:1.8.9-1890-4.2.0-BETA-1538]
        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:185) [SpongeImpl.class:1.8.9-1890-4.2.0-BETA-1538]
        at org.spongepowered.common.SpongeImpl.postShutdownEvents(SpongeImpl.java:189) [SpongeImpl.class:1.8.9-1890-4.2.0-BETA-1538]
        at net.minecraft.server.dedicated.DedicatedServer.handler$postGameStoppingEvent$0(DedicatedServer.java:73) [ko.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71240_o(DedicatedServer.java) [ko.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:545) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
`

**Comment by KaiKikuchi** [comment]
Hello. That error happens if SynX wasn't initialized properly. Probably you haven't configured it correctly. Specify your MySQL server info correctly on the synx.conf file.
